plugins {
    id 'com.android.library'
}

android {
    namespace 'com.fntv.app.api'
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 32
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.squareup.retrofit2:retrofit:2.6.4'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.4'
    implementation 'com.squareup.okhttp3:okhttp:3.12.13'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.13'
    implementation 'com.google.code.gson:gson:2.8.9'
}
