plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fntv.app'
    compileSdkVersion 33

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 32
        versionCode 18
        versionName "1.2.0"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }

    flavorDimensions "platform"
    productFlavors {
        tv {
            dimension "platform"
            applicationId "com.fntv.app"
            resValue "string", "app_name", "FN TV"
            buildConfigField "boolean", "IS_TV", "true"
            buildConfigField "String", "PLATFORM", "\"tv\""
        }
        mobile {
            dimension "platform"
            applicationId "com.fntv.app.mobile"
            resValue "string", "app_name", "FN TV 手机版"
            buildConfigField "boolean", "IS_TV", "false"
            buildConfigField "String", "PLATFORM", "\"mobile\""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "FNTV_${variant.flavorName}_${variant.buildType.name}_v${variant.versionName}_${generateTime()}.apk"
        }
    }
}

static def generateTime() {
    return new java.text.SimpleDateFormat("yyyyMMdd_HHmm", Locale.CHINA).format(new Date())
}

dependencies {
    implementation project(':core-api')
    implementation project(':core-common')
    implementation project(':core-player')
    implementation project(':feature-danmu')

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'com.squareup.retrofit2:retrofit:2.6.4'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.4'
    implementation 'com.squareup.okhttp3:okhttp:3.12.13'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.13'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.18.7'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.18.7'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.18.7'
    implementation 'org.jellyfin.exoplayer:exoplayer-ffmpeg-extension:2.18.7+1'
}
